config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get root 'pages#home'
  get '/about', to: 'pages#about'

  resources :articles
  resources :users, except: [:new]

  get 'signup', to: 'users#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user

  validates :title,       presence: true,
                          length:   { minimum: 3, maximum: 50 }
  validates :description, presence: true,
                          length:   { minimum: 10, maximum: 3000 }
  validates :user_id,     presence: true

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :photo
  belongs_to :user
end

app/models/photo_like.rb
class PhotoLike < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :username,  presence:   true,
                        uniqueness: { case_sensitive: false },
                        length:     { minimum: 3, maximum: 25 }
  validates :email,     presence:   true,
                        uniqueness: { case_sensitive: false },
                        length:     { maximum: 105 },
                        format:     { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
    set_article
  end

  def create
    # render plain: params[:article].inspect
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save
      flash[:success] = "Article succsessfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    set_article
    if @article.update(article_params)
      flash[:success] = "Article succsessfully edited"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
    set_article
  end

  def destroy
    set_article
    @article.delete
    flash[:danger] = "Article succsessfully deleted"
    redirect_to articles_path
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

  def about

  end

  def articles

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "Welcome to AlphaBlog #{@user.username}"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Your account was updated"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{ size }"
    image_tag(gravatar_url, alt: user.username, class: "rounded-circle")
  end
end

app/views/articles/_articles.html.erb
<% obj.each do |article| %>
  <div class='card mt-4'>
    <h2 class='card-header'><%= link_to article.title, article_path(article) %></h2>
    <div class='card-block'>
      <div class='card-text mb-2'>
        <%= truncate(article.description, length: 250) %>
        <div class='article-meta-details'>
        <small>
          <p>
            Created by: <%= article.user.username if article.user %>
            <%= time_ago_in_words(article.created_at) %> ago
            <br />
            Last updated: <%= time_ago_in_words(article.created_at) %> ago
          </p>
        </small>
        </div>
      </div>
      <div class="article-actions">
        <%= link_to 'Edit',   edit_article_path(article),
                              class: 'btn btn-primary btn-sm' %>
        <%= link_to 'Show',   article_path(article), 
                              class: 'btn btn-info btn-sm' %>
        <%= link_to 'Delete', article_path(article),
                              method: :delete,
                              data:   {confirm: 'Are you sure?' },
                              class:  'btn btn-danger btn-sm' %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@article, html: { class: 'form-horizontal', role: 'form' }) do |f| %>
      <div class="form-group row">
        <div class="col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title,  class:        'form-control', 
                                    placeholder:  'Title of article', 
                                    autofocus:    true %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, class:        'form-control', 
                                        placeholder:  'Body of article', 
                                        rows:         10 %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-10 offset-sm-2">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
          <%= link_to 'Cancel', articles_path,  class: 'btn btn-danger btn-lg', 
                                                role: 'button' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= link_to 'Home', root_path %>
<%= link_to 'about', about_path %>

<%= render 'form' %>

app/views/articles/index.html.erb
<%= render 'articles', obj: @articles %>

app/views/articles/new.html.erb
<h1 align='center'>Create New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class='card mt-4'>
  <h2 class='card-header'><%= @article.title %></h2>
  <div class='card-block'>
    <div align='center'>
      <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
      <div class="card-block">
        <div class="card-title">
          <%= link_to @article.user.username, user_path(@article.user) %>
        </div>
        <div class="card-text">
          <small>
            <%= pluralize(@article.user.articles.count, 'article') if @article.user.articles %>
          </small>
        </div>
      </div>
    </div>
    <div class='card-text'>
      <%= simple_format(@article.description) %>
    </div>
    <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-primary btn-sm' %>
    <%= link_to 'Back', articles_path, class: 'btn btn-info btn-sm' %>
    <%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy Chris Robertson 2017
    </small>
    <nav>
      <ul>
        <li>
          <%= link_to "About", about_path %> 
        </li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class='alert alert-<%="#{name}"%> alert-dismissible fade show mt-2' role='alert'>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<%# <nav class="navbar navbar-inverse bg-primary"> %>
<%#     <!-- Navbar content --> %>
<%# </nav> %>

<nav class="navbar navbar-toggleable-md navbar-inverse bg-primary">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand" %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "articles", articles_path, class: "nav-link" %><span class="sr-only">(current)</span>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Actions</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "New article", new_article_path, class: 'dropdown-item' %>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= stylesheet_link_tag    'custom', media: 'all', 'data-turbolinks-track': 'reload' %1> %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <div class="card mt-4">
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<%= link_to 'Home', root_path %>
<%= link_to 'Articles', articles_path %>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1 class="display-3">ALPHA BLOG</h1>
  <p class="lead">
  <a class="btn btn-primary btn-lg" href="#" role="button">Sign Up</a>
  </p>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |msg| %>
    <div class='alert alert-danger alert-dismissible fade show' role='alert'>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="row mt-4">
  <div class="col-md-12">
    <%= form_for(@user, html: { class: 'form-horizontal', role: 'form' }) do |f| %>
      <div class="form-group row">
        <div class="col-sm-2">
          <%= f.label :username %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username, class:        'form-control', 
                                      placeholder:  'Enter username', 
                                      autofocus:    true %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-2">
          <%= f.label :email %>
        </div>
        <div class="col-sm-8">
          <%= f.email_field :email, class:        'form-control', 
                                    placeholder:  'Enter email'%>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-2">
          <%= f.label :password %>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password, class:        'form-control', 
                                          placeholder:  'Enter password'%>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-10 offset-sm-2">
          <%= f.submit(@user.new_record? ? 'Signup' : 'Update', class: 'btn btn-primary btn-lg') %>
          <%= link_to 'Cancel', articles_path,  class: 'btn btn-danger btn-lg', 
                                                role: 'button' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit Your Account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align='center'>List of Users</h1>

<% @users.each do |user| %>
  <div class="card">
    <div align='center'>
      <%= link_to gravatar_for(user), user_path(user) %>
      <div class="card-block">
        <div class="card-title">
          <%= link_to user.username, user_path(user) %>
        </div>
        <div class="card-text">
          <small>
            <%= pluralize(user.articles.count, 'article') if user.articles %>
          </small>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<h1 align="center">Sign up for AlphaBlog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align='center'>
  Welcome <%= @user.username %>!
</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>
<h4 align='center'>
  <%= @user.username %>'s articles'
</h4>
<%= render 'articles/articles', obj: @user.articles %>